# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/michael-pro/repos/TWOe-viewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/michael-pro/repos/TWOe-viewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michael-pro/repos/TWOe-viewer/CMakeFiles /Users/michael-pro/repos/TWOe-viewer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michael-pro/repos/TWOe-viewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TWOe-viewer

# Build rule for target.
TWOe-viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TWOe-viewer
.PHONY : TWOe-viewer

# fast build rule for target.
TWOe-viewer/fast:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/build
.PHONY : TWOe-viewer/fast

src/MainViewWidget.o: src/MainViewWidget.cpp.o

.PHONY : src/MainViewWidget.o

# target to build an object file
src/MainViewWidget.cpp.o:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/MainViewWidget.cpp.o
.PHONY : src/MainViewWidget.cpp.o

src/MainViewWidget.i: src/MainViewWidget.cpp.i

.PHONY : src/MainViewWidget.i

# target to preprocess a source file
src/MainViewWidget.cpp.i:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/MainViewWidget.cpp.i
.PHONY : src/MainViewWidget.cpp.i

src/MainViewWidget.s: src/MainViewWidget.cpp.s

.PHONY : src/MainViewWidget.s

# target to generate assembly for a file
src/MainViewWidget.cpp.s:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/MainViewWidget.cpp.s
.PHONY : src/MainViewWidget.cpp.s

src/TwoeUnits.o: src/TwoeUnits.cpp.o

.PHONY : src/TwoeUnits.o

# target to build an object file
src/TwoeUnits.cpp.o:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/TwoeUnits.cpp.o
.PHONY : src/TwoeUnits.cpp.o

src/TwoeUnits.i: src/TwoeUnits.cpp.i

.PHONY : src/TwoeUnits.i

# target to preprocess a source file
src/TwoeUnits.cpp.i:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/TwoeUnits.cpp.i
.PHONY : src/TwoeUnits.cpp.i

src/TwoeUnits.s: src/TwoeUnits.cpp.s

.PHONY : src/TwoeUnits.s

# target to generate assembly for a file
src/TwoeUnits.cpp.s:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/TwoeUnits.cpp.s
.PHONY : src/TwoeUnits.cpp.s

src/TwoeViewer.o: src/TwoeViewer.cpp.o

.PHONY : src/TwoeViewer.o

# target to build an object file
src/TwoeViewer.cpp.o:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/TwoeViewer.cpp.o
.PHONY : src/TwoeViewer.cpp.o

src/TwoeViewer.i: src/TwoeViewer.cpp.i

.PHONY : src/TwoeViewer.i

# target to preprocess a source file
src/TwoeViewer.cpp.i:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/TwoeViewer.cpp.i
.PHONY : src/TwoeViewer.cpp.i

src/TwoeViewer.s: src/TwoeViewer.cpp.s

.PHONY : src/TwoeViewer.s

# target to generate assembly for a file
src/TwoeViewer.cpp.s:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/TwoeViewer.cpp.s
.PHONY : src/TwoeViewer.cpp.s

src/ViewWidget.o: src/ViewWidget.cpp.o

.PHONY : src/ViewWidget.o

# target to build an object file
src/ViewWidget.cpp.o:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/ViewWidget.cpp.o
.PHONY : src/ViewWidget.cpp.o

src/ViewWidget.i: src/ViewWidget.cpp.i

.PHONY : src/ViewWidget.i

# target to preprocess a source file
src/ViewWidget.cpp.i:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/ViewWidget.cpp.i
.PHONY : src/ViewWidget.cpp.i

src/ViewWidget.s: src/ViewWidget.cpp.s

.PHONY : src/ViewWidget.s

# target to generate assembly for a file
src/ViewWidget.cpp.s:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/ViewWidget.cpp.s
.PHONY : src/ViewWidget.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/TWOe-viewer.dir/build.make CMakeFiles/TWOe-viewer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TWOe-viewer"
	@echo "... src/MainViewWidget.o"
	@echo "... src/MainViewWidget.i"
	@echo "... src/MainViewWidget.s"
	@echo "... src/TwoeUnits.o"
	@echo "... src/TwoeUnits.i"
	@echo "... src/TwoeUnits.s"
	@echo "... src/TwoeViewer.o"
	@echo "... src/TwoeViewer.i"
	@echo "... src/TwoeViewer.s"
	@echo "... src/ViewWidget.o"
	@echo "... src/ViewWidget.i"
	@echo "... src/ViewWidget.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

